spring.application.name=jashan
spring.datasource.url=jdbc:postgresql://localhost:5432/queue
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Security
spring.security.user.name=jashan
spring.security.user.password=aaa
jwt.secretkey="euchecuh9y-98387038eyhwicuhfq98r9847108fu-c-1uf109cnwdwuweyg95gwy89w"



